### ISSUE TITLE
Why is the name not just SuiteSparse.jl?

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLinearAlgebra/SuiteSparseNext.jl#1]

**Comment by andreasnoack** [comment]
It seems that the package manager can't handle a package with the same name as a stdlib package. Hence I added the `Next` part. I assume that it should be possible to remove it once `SuiteSparse` has been deleted from stdlib.

**Comment by ViralBShah** [comment]
Good to know. Thanks.
